In [2]:
from logistic_regression import LogisticRegression
import numpy as np

In [10]:
AND_Gate = LogisticRegression(2, max_iterations=10, learning_rate=0.01)
X_train = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_train = np.array([0, 0, 0, 1])
AND_Gate.fit(X_train, y_train, batch_size=2, verbose=True)

[[0 0]
 [0 1]]
[[1 0]
 [1 1]]
[[0 0]
 [0 1]]
[[1 0]
 [1 1]]
[[0 0]
 [0 1]]
[[1 0]
 [1 1]]
[[0 0]
 [0 1]]
[[1 0]
 [1 1]]
[[0 0]
 [0 1]]
[[1 0]
 [1 1]]
[[0 0]
 [0 1]]
[[1 0]
 [1 1]]
[[0 0]
 [0 1]]
[[1 0]
 [1 1]]
[[0 0]
 [0 1]]
[[1 0]
 [1 1]]
[[0 0]
 [0 1]]
[[1 0]
 [1 1]]
[[0 0]
 [0 1]]
[[1 0]
 [1 1]]
